### ISSUE TITLE
[BUG] Flight not working, panel does not show on/off/auto

### ISSUE THREAD

**Issue by laxdragon** [Mattshark89/OpenFlight-VRC#33] opened 2023-06-23 15:54 UTC
**Describe the bug**

Flight is not working correctly in my world. I installed using VCC and added the prefab from the menu. The in world tablet where it is supposed to report that the mode is on or off reports nothing, it also does not show any detected avatar data.

When building my world, unity reports this error.

```
[UdonSharp] Packages/com.mattshark.openflight/Runtime/Scripts/Detection/AvatarDetection.cs(88,69): Udon runtime exception detected!
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__GetBonePosition__UnityEngineHumanBodyBones__UnityEngineVector3'.
      Parameter Addresses: 0x00000003, 0x00000020, 0x00000079
  Object reference not set to an instance of an object
```

**Screenshots**

![Screenshot 2023-06-23 104847](https://github.com/Mattshark89/OpenFlight-VRC/assets/1074320/2e8fe35a-5978-4ffb-8ff0-37c591c61328)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 
 - VRC SDK Version: 3.2.1
 - UdonSharp Version: 1.1.8

**Comment by Happyrobot33** [comment] 2023-06-27 19:29
Just saw this, dont know why im not getting notifications for issues in this repository yet, but im going to look into this ASAP

**Comment by Happyrobot33** [comment] 2023-06-27 19:34
Relevant line
https://github.com/Mattshark89/OpenFlight-VRC/blob/1b0c5f27c49323006325a16abd020c6ca73d2032/Packages/com.mattshark.openflight/Runtime/Scripts/Detection/AvatarDetection.cs#L88

**Comment by Mattshark89** [comment] 2023-06-28 03:59
Can confirm the latest version is not broken out of the box, did a quick fresh install myself of the system including the tablet (Full). Something odd must have happened in the Unity Project, still worth looking into

**Comment by laxdragon** [comment] 2023-06-28 12:31
Thanks for spending so much time trying to figure this out. Unity has done something odd to my world due to a previous editor crash. Something somewhere is corrupt. Easier to just rebuild and move on.

**Comment by Happyrobot33** [comment] 2023-06-28 12:35
Un-Reproducable as of now by anyone but end user, changing status to not planned. If there is any updates to this feel free to comment in here about it

**Comment by Happyrobot33** [comment] 2023-09-30 07:19
reopening due to atomiklan also encountering this issue

**Comment by Happyrobot33** [comment] 2023-09-30 16:16
Reproduction steps: Place tablet far enough away from the player that upon the world loading it will be faded out automatically

Something about the way hiding it works it just seems to break the UI scripts

**Comment by Happyrobot33** [comment] 2023-09-30 16:45
possibly closed by latest beta

**Comment by Happyrobot33** [comment] 2023-09-30 23:39
Closed as fixed

**Closed by Happyrobot33** 2023-09-30 23:39 UTC
Labels: bug, question

**Comment by laxdragon** [comment] 2023-10-01 03:57
All good here. I know this is closed. But just wanted to report the latest beta works for me. Good work!
